### ISSUE TITLE
ECOPO开源计划

### ISSUE THREAD

**Issue by xdnjust** [geekjuruo/ProbExpan#1]
楼主大佬您好，

最近我们教研室讨论了您的ACL22大作ECOPO算法，关于中文纠错的，我们老师希望我们复现出来

请问一下代码有开源计划吗？不好意思在这里发言寻求帮助

**Comment by geekjuruo** [comment]
您好，关于ECOPO的相关问题，可以给我发邮件或者添加微信咨询，liyinghu20@mails.tsinghua.edu.cn (lyh62125685 )
