### ISSUE TITLE
关于SE2数据集 处理的问题

### ISSUE THREAD

**Issue by Delicate2000** [geekjuruo/ProbExpan#2]
您好，我这边下载SE2数据集的vocabulary.txt有150W个实体，请问您在处理该数据集时有初筛的过程嘛，还是直接将150W实体作为候选实体集？

**Comment by geekjuruo** [comment]
您好，SE2数据集的确很大，需要跑很久时间～

**Comment by Delicate2000** [comment]
您好，SE2数据集中corpus.txt.zip文件我这里下载完解压显示文件已损坏。您当时有遇到类似的问题嘛，是否方便提供下这个文件。

**Comment by geekjuruo** [comment]
我印象中遇到过（抱歉时间过得太久印象不深了），本地PC解压有问题，放到Linux服务器上用命令解压就好了好像。
